### ISSUE TITLE
Terminus Signaling Beacon missing for melee specs

### ISSUE THREAD

**Issue by h1054481** [Bloodmallet/bloodmallet.github.io#67] opened 2018-07-18 21:22 UTC
Hey appreciate the great work and effort but i cant find the trinket "terminus signaling beacon" for melee dps in the sims on AOE for example. For ranges it shows up but not for melee. Is that intentional? For example i am a fury warrior and Id like to use it.

**Comment by Bloodmallet** [comment] 2018-07-18 21:31
Greetings,
thank you for asking. This trinket is not flagged to drop for melees, therefore I think it has some sort of downscaling applied to its damage for melees. I'd rather not add it, unless this trinket isn't scaled down.

Let me know if it deals as much damage for you as it does for specs that can get it via personal loot.

**Comment by h1054481** [comment] 2018-07-18 21:54
thanks for the fast response- dont have any details! reports to back it up atm but i used it over glaives before the prepatch cause it did significantly more dmg. gonna test it on prepatch values

**Comment by h1054481** [comment] 2018-07-18 22:40
update: went with my buddy on the dummies in og to test the trinket- he has it 245 mine is 240 - checked the damage and its roughly the same- average hit as a fury warrior 256 (28,6% crit 7,5% versa) was 2,5k and crit was 4,7k. for the frost mage with 240 ilvl( 32% crit 16% versa) it did 2,7k and crit was 5,2k with incanters flow active. So i think its worth considering it in the sims.

**Comment by Bloodmallet** [comment] 2018-07-19 11:36
Thank you for looking into it. I enabled this trinket for melees last night and a new simulation just finished. This one should have the trinket.
New data should be published in a few minutes. But having a quick look at the simulation data doesn't seem very promising. This could be either because the fight context doesn't show the strength of this trinket, the trinket has some interactions with Fury effects that aren't in SimulationCraft, or the trinket is just not as strong.
If you like to investigate this issue further, it would be helpful to create your own sims for this trinket. Try to find the cause and get it fixed in SimulationCraft. ❤️ 

I'm closing the issue for now, but tell me, if something about this trinket changes, so I can rerun everything.

**Closed by Bloodmallet** 2018-07-19 11:36 UTC
