### ISSUE TITLE
Outlaw Rogue Talents AOE

### ISSUE THREAD

**Issue by imp0** [Bloodmallet/bloodmallet.github.io#164] opened 2019-10-28 08:34 UTC
Hello !

I just want to point out that the talents on **Hectic Add Cleave** for **Outlaw Rogue** include the 100lvl talent to be Blade Rush. This might be wrong, cause Outlaw Rogues run Dancing Steel as 100lvl talent in AOE/Cleave fights.

Keep up the good work :D 
Imp0

**Comment by Bloodmallet** [comment] 2019-10-29 18:50
Greetings,

all data on bloodmallet.com uses the standard profiles of SimulationCraft. There aren't profiles for HecticAddCleave, which means, that the standard single target profiles are used, too. I can see (and agree) that this is no ideal. I know that there are some DungeonSlice profiles (someone copied all patchwerk profiles as a baseline for DungeonSlice and some specs started updating that for AoE). But I'm unsure how well maintained those are, or if they even would properly fit HecticAddCleave, because that's yet another different fight style and not DungeonSlice. I'm reluctant to provide "my own" (community driven) profiles or profile changes, but want to stick to easily reproduceable data, therefore I need to stick to the standard profiles of SimulationCraft for now. I have some things in the pipeline, that might enable a change to this in the future. So stay tuned (but don't expect anything too soon).

Thank you for reaching out! As I don't see a solution to your question, I'm going to close the issue. Feel free to reopen it, if there is some input I'm missing.

Yours sincerely,
Bloodmallet(EU)

**Closed by Bloodmallet** 2019-10-29 18:50 UTC
Labels: wontfix
