### ISSUE TITLE
Links from under chart tooltips shine through after category updates

### ISSUE THREAD

**Issue by Kutikuti** [Bloodmallet/bloodmallet.github.io#37] opened 2017-12-14 16:26 UTC
When hovering amanthul +10/15/20 : https://cdn.discordapp.com/attachments/244087483476738051/390898977526120448/unknown.png

**Comment by Bloodmallet** [comment] 2018-01-18 16:22
An update is rolling out, that should fix this problem.

**Comment by Kutikuti** [comment] 2018-01-19 11:36
not quite : 
https://imgur.com/q95Dil9

Seems like the white box in not big enough (there is space between border and background)

**Comment by Bloodmallet** [comment] 2018-01-19 12:09
oha...looks like i need to recheck that again. I thought I made it big enough. I might've lost a change somewhere. Thank you for catching it. If you happen to know a working value, please let me know.

**Comment by Bloodmallet** [comment] 2018-07-23 12:59
Probelm is still occuring...
![image](https://user-images.githubusercontent.com/9075987/43077849-ee6536c4-8e88-11e8-9cc2-d99cf32e026d.png)

**Comment by Bloodmallet** [comment] 2018-07-24 09:37
Somehow the problem is not reproduceable today. It's...confusing.

**Comment by Bloodmallet** [comment] 2018-08-30 13:37
Should be fixed by adding
```css
.highcharts-tooltip {
  z-index:100;
}
```

**Closed by Bloodmallet** 2018-08-30 13:37 UTC
